name: CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        cd django_backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Django checks
      run: |
        cd django_backend
        python manage.py check

    - name: Run Django tests
      run: |
        cd django_backend
        python manage.py test

